# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy live Site TRX subdomain

on:
  push:
    branches: [ main-trx ]

  workflow_dispatch:
    
jobs:
  build:

    runs-on: self-hosted

    defaults:
      run:
        working-directory: trx-interface

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main-trx'
        path: 'trx-interface'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cp .env.production .env
    - run: npm i
    - run: CI=false npm run build
    - run: rsync -av /root/actions-runner/_work/intercroneswap-interface/intercroneswap-interface/trx-interface/build/ /var/www/html/trx-interface/
